dump_dir: ../
name: fan
steps: 60_000
probe_freq: null
seed: 777

optim:
  lr: 3e-3
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.00001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 2048
  n_layers: 12
  attention:
    n_heads: 16
  mlp:
    ffn_type: fan

data:
  root_dir: /leonardo_work/BOOST_LCustodi/script/training/lingua/data/
  sources:
    fineweb_edu_350bt_shuffled: 100.0
  batch_size: 10
  prefetch_size: 1024
  seq_len: 4096
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: sp
    path: /leonardo_work/BOOST_LCustodi/script/training/lingua/tokenizers/tokenizer_llama2.model

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 2500
    keep: 3
  eval:
    every: 5000
    keep: -1

logging:
  freq: 1
  wandb:
    name : fan


async_eval_gpus: 4
eval:
  harness:
    tasks:
      - hellaswag
      - nq_open
      - task: piqa
        dataset_kwargs:
          trust_remote_code: true
      - social_iqa
      - task: winogrande
        dataset_kwargs:
          trust_remote_code: true
      - arc_easy
      - arc_challenge
      - race
      - gsm8k
      - bbh
      #- mmlu
      - mmlu_pro
      #- mgsm_direct
      #- mgsm_cot_native
      #- french_bench
      #- agieval_en
      #- agieval_cn
      #- spanish_bench
      - squad_completion
      # - squadv2
      - drop
      #- ifeval

  generator:
    max_tokens: 4096
    dtype: bf16
